[tool.poetry]
name = "shopp"
version = "0.1.0"
description = ""
authors = ["Айрат <airat.nevretdinov@gamil.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
